version: '3'
services:
  go-server:
    image: gocd/gocd-server:v18.9.0
    container_name: go-server
    restart: always
    ports:
      - "8153:8153"
      - "8154:8154"
    volumes:
      - ./godata/config/cruise-config.xml:/godata/config/cruise-config.xml
      - /mnt/gocd-data:/godata
      - /mnt/gocd-home:/home/go
    networks:
      - gocd_network
  go-agent1:
    image: gocd/gocd-agent-alpine-3.5:v18.9.0
    container_name: go-agent1
    restart: always
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: https://go-server:8154/go
    networks:
      - gocd_network
  go-agent2:
    image: gocd/gocd-agent-alpine-3.5:v18.9.0
    container_name: go-agent2
    restart: always
    links:
      - "go-server"
    depends_on:
      - "go-server"
    environment:
      AGENT_AUTO_REGISTER_KEY: '123456789abcdefgh987654321'
      GO_SERVER_URL: https://go-server:8154/go
    networks:
      - gocd_network
networks:
  gocd_network:
